seeds:

## EXAMPLE SEEDS ##
  - domain: news.ycombinator.com
    priority: 100
    start_urls:
      - https://news.ycombinator.com/
      - https://news.ycombinator.com/newest
      - https://news.ycombinator.com/front
      - https://news.ycombinator.com/show
